export const employeeDetailsLang = {
  en: {
    title: "Employee Logs",
    backToAdmin: "← Back to Admin",
    employeeList: "👥 Employee List",
    manageLeave: "📆 Manage Leave",
    year: "Year:",
    month: "Month:",
    startDate: "Start Date:",
    endDate: "End Date:",
    totalSessions: "Total sessions:",
    totalOvertime: "Total overtime:",
    createSession: "＋ Create Session",
    createSessionTitle: "Create Manual Session",
    type: "Type:",
    work: "Work",
    paidLeave: "Paid Leave",
    unpaidLeave: "Unpaid Leave",
    checkIn: "Check-in:",
    checkOut: "Check-out:",
    submit: "Submit",
    cancel: "Cancel",
    employmentTitle: "Employment Info",
    joinDate: "Join Date:",
    employmentType: "Employment Type:",
    fullTime: "Full-Time",
    partTime: "Part-Time",
    weeklyDays: "Weekly Working Days:",
    defaultStartTime: "Default Start Time:",
    shiftWorker: "Shift Worker:",
    yes: "Yes",
    no: "No",
    employmentTypeDisplay: "Employment Type:",
    shiftWorkerDisplay: "Shift Worker:",
    leaveBalance: "Leave Balance:",
    saveInfo: "💾 Save Info",
    shiftAssignTitle: "Monthly Shift Assignment",
    shiftMonth: "Month:",
    saveShift: "💾 Save Shift",
    openCreateSession: "＋ Create Session",
    pageTitle: "Employee Check-In Records",
    monday: "Monday",
    tuesday: "Tuesday",
    wednesday: "Wednesday",
    thursday: "Thursday",
    friday: "Friday",
    saturday: "Saturday",
    sunday: "Sunday",
    lateNotice: "🚨 Late by {hh}:{mm}",
    sessionUpdated: "✅ Session updated!",
    sessionDeleted: "🗑️ Session deleted.",
    deleteFailed: "❌ Failed to delete session.",
    updateFailed: "❌ Failed to update session.",
    requestFailed: "❌ Request failed.",
    confirmDelete: "Are you sure you want to delete this session?",
    fillInTime: "⛔ Please fill in both check-in and check-out times.",
    invalidInput: "❌ Invalid date input.",
    checkOutAfter: "⚠️ Check-out must be after check-in.",
    sessionCreated: "✅ Session created.",
    createFailed: "❌ Failed to create session.",
    exportExcel: '📥 Export Excel',
    table: {
      checkIn: "Check In",
      checkOut: "Check Out",
      worked: "Worked",
      overtime: "Overtime",
      type: "Type",
      night: "Night Work",
      actions: "Actions"
    }
  },
  ja: {
    title: "勤務記録",
    backToAdmin: "← 管理画面に戻る",
    employeeList: "👥 社員一覧",
    manageLeave: "📆 休暇管理",
    year: "年:",
    month: "月:",
    startDate: "開始日:",
    endDate: "終了日:",
    totalSessions: "勤務回数:",
    totalOvertime: "残業合計:",
    createSession: "＋ 勤務を追加",
    createSessionTitle: "手動勤務の追加",
    type: "種別:",
    work: "勤務",
    paidLeave: "有給",
    unpaidLeave: "無給",
    checkIn: "出勤:",
    checkOut: "退勤:",
    submit: "送信",
    cancel: "キャンセル",
    employmentTitle: "雇用情報",
    joinDate: "入社日:",
    employmentType: "雇用形態:",
    fullTime: "フルタイム",
    partTime: "パートタイム",
    weeklyDays: "週勤務日数:",
    defaultStartTime: "開始時刻:",
    shiftWorker: "シフト勤務:",
    yes: "はい",
    no: "いいえ",
    employmentTypeDisplay: "雇用形態:",
    shiftWorkerDisplay: "シフト勤務:",
    leaveBalance: "有給残高:",
    saveInfo: "💾 情報を保存",
    shiftAssignTitle: "月間シフト割当",
    shiftMonth: "対象月:",
    saveShift: "💾 シフト保存",
    openCreateSession: "＋ 勤務を追加",
    pageTitle: "社員の勤務記録",
    monday: "月曜日",
    tuesday: "火曜日",
    wednesday: "水曜日",
    thursday: "木曜日",
    friday: "金曜日",
    saturday: "土曜日",
    sunday: "日曜日",
    lateNotice: "🚨 {hh}:{mm} 遅刻",   
    sessionUpdated: "✅ セッションが更新されました！",
    sessionDeleted: "🗑️ セッションを削除しました。",
    deleteFailed: "❌ セッションの削除に失敗しました。",
    updateFailed: "❌ セッションの更新に失敗しました。",
    requestFailed: "❌ リクエストが失敗しました。",
    confirmDelete: "このセッションを削除してもよろしいですか？",
    fillInTime: "⛔ 出勤・退勤時間を入力してください。",
    invalidInput: "❌ 日時の入力が正しくありません。",
    checkOutAfter: "⚠️ 退勤は出勤より後の時刻にしてください。",
    sessionCreated: "✅ セッションを作成しました。",
    createFailed: "❌ セッションの作成に失敗しました。",
    exportExcel: '📥 エクセル出力',
    table: {
      checkIn: "出勤",
      checkOut: "退勤",
      worked: "勤務時間",
      overtime: "残業",
      type: "種別",
      night: "深夜勤務",
      actions: "操作"
    }
  }
};
