export const employeeDetailsLang = {
  en: {
    title: "Employee Logs",
    backToAdmin: "← Back to Admin",
    employeeList: "👥 Employee List",
    manageLeave: "📆 Manage Leave",
    year: "Year:",
    month: "Month:",
    startDate: "Start Date:",
    endDate: "End Date:",
    totalSessions: "Total sessions:",
    totalOvertime: "Total overtime:",
    createSession: "＋ Create Session",
    createSessionTitle: "Create Manual Session",
    type: "Type:",
    work: "Work",
    paidLeave: "Paid Leave",
    unpaidLeave: "Unpaid Leave",
    checkIn: "Check-in:",
    checkOut: "Check-out:",
    submit: "Submit",
    cancel: "Cancel",
    employmentTitle: "Employment Info",
    joinDate: "Join Date:",
    employmentType: "Employment Type:",
    fullTime: "Full-Time",
    partTime: "Part-Time",
    weeklyDays: "Weekly Working Days:",
    defaultStartTime: "Default Start Time:",
    shiftWorker: "Shift Worker:",
    yes: "Yes",
    no: "No",
    employmentTypeDisplay: "Employment Type:",
    shiftWorkerDisplay: "Shift Worker:",
    leaveBalance: "Leave Balance:",
    saveInfo: "💾 Save Info",
    shiftAssignTitle: "Monthly Shift Assignment",
    shiftMonth: "Month:",
    saveShift: "💾 Save Shift",
    table: {
      checkIn: "Check In",
      checkOut: "Check Out",
      worked: "Worked",
      overtime: "Overtime",
      type: "Type",
      night: "Night Work",
      actions: "Actions"
    }
  },
  ja: {
    title: "勤務記録",
    backToAdmin: "← 管理画面に戻る",
    employeeList: "👥 社員一覧",
    manageLeave: "📆 休暇管理",
    year: "年:",
    month: "月:",
    startDate: "開始日:",
    endDate: "終了日:",
    totalSessions: "勤務回数:",
    totalOvertime: "残業合計:",
    createSession: "＋ 勤務を追加",
    createSessionTitle: "手動勤務の追加",
    type: "種別:",
    work: "勤務",
    paidLeave: "有給",
    unpaidLeave: "無給",
    checkIn: "出勤:",
    checkOut: "退勤:",
    submit: "送信",
    cancel: "キャンセル",
    employmentTitle: "雇用情報",
    joinDate: "入社日:",
    employmentType: "雇用形態:",
    fullTime: "フルタイム",
    partTime: "パートタイム",
    weeklyDays: "週勤務日数:",
    defaultStartTime: "開始時刻:",
    shiftWorker: "シフト勤務:",
    yes: "はい",
    no: "いいえ",
    employmentTypeDisplay: "雇用形態:",
    shiftWorkerDisplay: "シフト勤務:",
    leaveBalance: "有給残高:",
    saveInfo: "💾 情報を保存",
    shiftAssignTitle: "月間シフト割当",
    shiftMonth: "対象月:",
    saveShift: "💾 シフト保存",
    table: {
      checkIn: "出勤",
      checkOut: "退勤",
      worked: "勤務時間",
      overtime: "残業",
      type: "種別",
      night: "深夜勤務",
      actions: "操作"
    }
  }
};
